### ISSUE TITLE
很棒的扩展, 能否考虑折腾个兼容最新Chrome版本的呢 ?

### ISSUE THREAD

**Issue by mike652638** [jhrxx/CORS-dev-tool#1]
配置挺丰富, 很实用的小工具, 但貌似目前没有兼容Chrome浏览器? 有的话则更好了 :)

**Comment by jhrxx** [comment]
很早就发布了。。。。
https://chrome.google.com/webstore/detail/cors-helper/jckpaobldaolbbchaeicopkcljcaiaka
